In [1]:
import pandas as pd

df = pd.read_csv("../dataset/housing_price.csv")

In [2]:
df.dtypes

Date                      object
City                      object
Area_sqft                  int64
Bedrooms                   int64
Bathrooms                  int64
Floors                     int64
Parking                    int64
Year_Built                 int64
Property_Age               int64
Location_Rating          float64
Distance_to_Center_km      int64
Nearby_Schools             int64
Nearby_Hospitals           int64
Nearby_Malls               int64
Crime_Rate               float64
Price_per_Sqft             int64
Total_Price                int64
Loan_Eligible             object
Property_Type             object
Listing_Status            object
dtype: object

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   5 non-null      object
 1   City                   5 non-null      object
 2   Area_sqft              5 non-null      int64
 3   Bedrooms               5 non-null      int64
 4   Bathrooms              5 non-null      int64
 5   Floors                 5 non-null      int64
 6   Parking                5 non-null      int64
 7   Year_Built             5 non-null      int64
 8   Property_Age           5 non-null      int64
 9   Location_Rating        5 non-null      float64
 10  Distance_to_Center_km  5 non-null      int64
 11  Nearby_Schools         5 non-null      int64
 12  Nearby_Hospitals       5 non-null      int64
 13  Nearby_Malls           5 non-null      int64
 14  Crime_Rate             5 non-null      float64
 15  Price_per_Sqft         5 non-null      int64
 16  Total_Price            5 non-null      int64
 17  Loan_Eligible          5 non-null      object
 18  Property_Type          5 non-null      object
 19  Listing_Status         5 non-null      object
dtypes: float64(2), int64(13), object(5)
memory usage: 932.0+ bytes

In [4]:
df["Total_Price"].dtype

dtype('int64')

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

In [6]:
df["Loan_Eligible"] = df["Loan_Eligible"].str.strip().str.lower()
df["Loan_Eligible"].head()

0    yes
1    yes
2    yes
3     no
4    yes
Name: Loan_Eligible, dtype: object

In [7]:
df.isnull()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
df.isnull().values.any()

np.False_

In [9]:
df.dropna()

,Date,City,Area_sqft,Bedrooms,Bathrooms,Floors,Parking,Year_Built,Property_Age,Location_Rating,Distance_to_Center_km,Nearby_Schools,Nearby_Hospitals,Nearby_Malls,Crime_Rate,Price_per_Sqft,Total_Price,Loan_Eligible,Property_Type,Listing_Status
0,2024-01-31,Hyderabad,1200,3,2,1,1,2015,9,4.5,10,3,2,1,2.1,4200,5040000,yes,Apartment,Available
1,2024-02-29,Chennai,1000,2,2,1,1,2012,12,4.2,8,2,2,1,2.5,4500,4500000,yes,Apartment,Sold
2,2024-03-31,Mumbai,1500,4,3,2,2,2018,6,4.8,5,4,3,2,1.8,6000,9000000,yes,Villa,Available
3,2024-04-30,Bangalore,1300,3,2,1,1,2016,8,4.6,7,3,2,1,2.0,5000,6500000,no,Apartment,Available
4,2024-05-31,Pune,1100,2,2,1,1,2014,10,4.3,9,2,2,1,2.3,4300,4730000,yes,Apartment,Sold

In [10]:
df["Crime_Rate"] = df["Crime_Rate"].fillna(df["Crime_Rate"].mean())
print(df["Crime_Rate"])

0    2.1
1    2.5
2    1.8
3    2.0
4    2.3
Name: Crime_Rate, dtype: float64

In [12]:
df["Parking"] = df["Parking"].fillna(0)
print(df["Parking"].isnull().sum())

0