In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv(r"C:/Users/dindu/OneDrive/Desktop/Realty AI/dataset/real_estate_dataset.csv")

In [9]:
df.head()

,url,beds,city,date,size,type,baths,price,neighborhood
0,https://www.99acres.com/residential-land-plot-...,0,Bangalore,2025-02-19,799-1258 sqft,Residential land / Plot,0,2317000.0,Jigani
1,https://www.99acres.com/2-bhk-bedroom-apartmen...,2,Bangalore,2025-02-19,1085 sqft,2 BHK Flat,2,12500000.0,Tumkur Road
2,https://www.99acres.com/sumadhura-capitol-resi...,3,Bangalore,2025-02-19,1525-2150 sqft,"3, 4 BHK Apartment",0,23200000.0,Whitefield
3,https://www.99acres.com/provident-botanico-sou...,2,Bangalore,2025-02-19,658-1003 sqft,"2, 3 BHK Apartment",0,889000.0,Soukya Road
4,https://www.99acres.com/kvg-superior-kalkere-b...,2,Bangalore,2025-02-19,1179-1449 sqft,"2, 3 BHK Apartment",0,6483000.0,Kalkere

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           287 non-null    object
 1   beds          287 non-null    int64
 2   city          287 non-null    object
 3   date          287 non-null    object
 4   size          287 non-null    object
 5   type          287 non-null    object
 6   baths         287 non-null    int64
 7   price         287 non-null    float64
 8   neighborhood  287 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 20.3+ KB

In [11]:
df.shape

(287, 9)

In [12]:
df.isnull().sum()

url             0
beds            0
city            0
date            0
size            0
type            0
baths           0
price           0
neighborhood    0
dtype: int64

In [5]:
df.describe()

             beds       baths         price
count  287.000000  287.000000  2.870000e+02
mean     2.156794    1.526132  1.956434e+07
std      1.767959    1.771525  4.461799e+07
min      0.000000    0.000000  0.000000e+00
25%      0.000000    0.000000  4.738000e+06
50%      2.000000    1.000000  1.000000e+07
75%      3.000000    2.000000  2.085000e+07
max     12.000000   12.000000  6.000000e+08

In [13]:
df.duplicated().sum()

0

In [14]:
numerical_df = df.select_dtypes(include=['int64', 'float64'])
numerical_df.corr()

           beds     baths     price
beds   1.000000  0.747224  0.020138
baths  0.747224  1.000000  0.034577
price  0.020138  0.034577  1.000000

In [15]:
print(df.columns)

Index(['url', 'beds', 'city', 'date', 'size', 'type', 'baths', 'price',
       'neighborhood'],
      dtype='object')

In [16]:
df_encoded = pd.get_dummies(df, columns=["type"])
df_encoded.head()

,url,beds,city,date,size,baths,price,neighborhood,type_1 BHK Flat,type_1 BHK Independent Builder Floor,...,type_Independent House/Villa,type_Land,type_Luxury Villa,type_Plot/Land,type_Residential Land,type_Residential apartment,type_Residential land / Plot,type_Residential property,type_Studio Apartments / 1 RK Flats,type_Villa
0,https://www.99acres.com/residential-land-plot-...,0,Bangalore,2025-02-19,799-1258 sqft,0,2317000.0,Jigani,False,False,...,False,False,False,False,False,False,True,False,False,False
1,https://www.99acres.com/2-bhk-bedroom-apartmen...,2,Bangalore,2025-02-19,1085 sqft,2,12500000.0,Tumkur Road,False,False,...,False,False,False,False,False,False,False,False,False,False
2,https://www.99acres.com/sumadhura-capitol-resi...,3,Bangalore,2025-02-19,1525-2150 sqft,0,23200000.0,Whitefield,False,False,...,False,False,False,False,False,False,False,False,False,False
3,https://www.99acres.com/provident-botanico-sou...,2,Bangalore,2025-02-19,658-1003 sqft,0,889000.0,Soukya Road,False,False,...,False,False,False,False,False,False,False,False,False,False
4,https://www.99acres.com/kvg-superior-kalkere-b...,2,Bangalore,2025-02-19,1179-1449 sqft,0,6483000.0,Kalkere,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
df_encoded = pd.get_dummies(
    df, 
    columns=["city", "type", "neighborhood"]
)

df_encoded.head()

,url,beds,date,size,baths,price,city_Agra,city_Bangalore,city_Bhubaneswar,city_Chennai,...,neighborhood_Wadala,neighborhood_Whitefield,neighborhood_Worli,neighborhood_Yelahanka,neighborhood_Yendada,neighborhood_balacheruvu road,neighborhood_good earth hamlet,neighborhood_nallasopara,neighborhood_sector 121,neighborhood_sheetal apartments
0,https://www.99acres.com/residential-land-plot-...,0,2025-02-19,799-1258 sqft,0,2317000.0,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,https://www.99acres.com/2-bhk-bedroom-apartmen...,2,2025-02-19,1085 sqft,2,12500000.0,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,https://www.99acres.com/sumadhura-capitol-resi...,3,2025-02-19,1525-2150 sqft,0,23200000.0,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,https://www.99acres.com/provident-botanico-sou...,2,2025-02-19,658-1003 sqft,0,889000.0,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,https://www.99acres.com/kvg-superior-kalkere-b...,2,2025-02-19,1179-1449 sqft,0,6483000.0,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [28]:
df = pd.get_dummies(df, columns=["type"], dtype=int)
df.head()

,url,beds,city,date,size,baths,price,neighborhood,type_0,type_1,...,type_38,type_39,type_40,type_41,type_42,type_43,type_44,type_45,type_46,type_47
0,0,0,0,0,0,0,2317000.0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,0,0,1,2,12500000.0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,3,0,0,2,0,23200000.0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2,0,0,3,0,889000.0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,2,0,0,4,0,6483000.0,4,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
df.shape

(287, 56)

In [30]:
df.head()

,url,beds,city,date,size,baths,price,neighborhood,type_0,type_1,...,type_38,type_39,type_40,type_41,type_42,type_43,type_44,type_45,type_46,type_47
0,0,0,0,0,0,0,2317000.0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,0,0,1,2,12500000.0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,3,0,0,2,0,23200000.0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2,0,0,3,0,889000.0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,2,0,0,4,0,6483000.0,4,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df["city"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25], dtype=int64)

In [32]:
df["neighborhood"].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223], dtype=int64)

In [18]:
# Select categorical columns
categorical_cols = df.select_dtypes(include='object').columns

In [19]:
# Apply Label Encoding using pandas factorize
for col in categorical_cols:
    df[col], _ = pd.factorize(df[col])

print("Encoding Completed")

Encoding Completed

In [20]:
correlation_matrix = df.corr()
print(correlation_matrix)

                   url      beds      city      date      size      type  \
url           1.000000 -0.135007  0.560512  0.124088  0.910173  0.385228
beds         -0.135007  1.000000 -0.147016  0.048833 -0.105795  0.160728
city          0.560512 -0.147016  1.000000 -0.118262  0.573880  0.223766
date          0.124088  0.048833 -0.118262  1.000000  0.111493  0.114250
size          0.910173 -0.105795  0.573880  0.111493  1.000000  0.408864
type          0.385228  0.160728  0.223766  0.114250  0.408864  1.000000
baths        -0.042851  0.747224 -0.078612  0.162758 -0.017713  0.203269
price        -0.031680  0.020138 -0.012640  0.006739 -0.043767 -0.097600
neighborhood  0.961782 -0.111160  0.578490  0.120448  0.865528  0.403469

                 baths     price  neighborhood
url          -0.042851 -0.031680      0.961782
beds          0.747224  0.020138     -0.111160
city         -0.078612 -0.012640      0.578490
date          0.162758  0.006739      0.120448
size         -0.017713 -0.043767      0.865528
type          0.203269 -0.097600      0.403469
baths         1.000000  0.034577     -0.025220
price         0.034577  1.000000     -0.027199
neighborhood -0.025220 -0.027199      1.000000