In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [9]:
# Displaying the dataset
df = pd.read_csv("../dataset/india_housing_prices.csv",index_col="ID")
df.head()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [6]:
df.shape

(250000, 23)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       250000 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 43.9+ MB

In [33]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = df.select_dtypes(include=["object"]).columns

numerical_cols, categorical_cols

(Index(['BHK', 'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
        'Floor_No', 'Total_Floors', 'Age_of_Property', 'Nearby_Schools',
        'Nearby_Hospitals'],
       dtype='object'),
 Index(['State', 'City', 'Locality', 'Property_Type', 'Furnished_Status',
        'Public_Transport_Accessibility', 'Parking_Space', 'Security',
        'Amenities', 'Facing', 'Owner_Type', 'Availability_Status'],
       dtype='object'))

## Analysis of Columns
**Target Column** - Price_per_SqFt  
**Numerical Columns**  
*(int64)*
1. ID
2. BHK
3. Size_in_SqFt
4. Year_Built
5. Floor_No
6. Total_Floors
7. Age_of_Property
8. Nearby_Schools
9. Nearby_Hospitals

*(float64)*
1. Price_in_Lakhs
2. Price_in_SqFt

**Categorical Columns**
1. State
2. City
3. Locality
4. Property_Type
5. Furnished_Status
6. Public_Transport_Accessibility
7. Parking_Space
8. Security
9. Amenities
10. Facing
11. Owner_Type
12. Availability_Status

## Checking for Null Values in columns

In [17]:
df.isna().sum() #No null vales present in the dataset

State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [19]:
df['Amenities'].head(10)

ID
1     Playground, Gym, Garden, Pool, Clubhouse
2     Playground, Clubhouse, Pool, Gym, Garden
3             Clubhouse, Pool, Playground, Gym
4     Playground, Clubhouse, Gym, Pool, Garden
5     Playground, Garden, Gym, Pool, Clubhouse
6                        Playground, Clubhouse
7                Clubhouse, Garden, Playground
8             Gym, Pool, Clubhouse, Playground
9                Garden, Clubhouse, Playground
10          Clubhouse, Playground, Garden, Gym
Name: Amenities, dtype: object

In [20]:
df.iloc[20:30,:]

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
21,Uttar Pradesh,Noida,Locality_286,Independent House,3,1270,475.78,0.37,2018,Semi-furnished,...,7,3,4,Medium,No,Yes,"Clubhouse, Gym, Garden, Pool, Playground",North,Owner,Under_Construction
22,Chhattisgarh,Bilaspur,Locality_74,Villa,5,4626,343.40,0.07,1990,Furnished,...,35,6,8,Low,Yes,Yes,"Pool, Clubhouse, Gym, Playground, Garden",East,Owner,Ready_to_Move
23,Telangana,Warangal,Locality_459,Apartment,1,2059,488.42,0.24,1995,Furnished,...,30,7,6,Low,No,No,"Garden, Pool, Gym, Playground, Clubhouse",West,Broker,Under_Construction
24,Rajasthan,Jaipur,Locality_355,Independent House,4,3176,164.31,0.05,1990,Unfurnished,...,35,9,4,Low,Yes,No,"Pool, Gym, Clubhouse",East,Builder,Under_Construction
25,Bihar,Gaya,Locality_151,Apartment,2,1925,322.81,0.17,2019,Unfurnished,...,6,9,6,High,Yes,Yes,"Garden, Clubhouse, Playground",North,Owner,Under_Construction
26,Jharkhand,Jamshedpur,Locality_159,Villa,3,2032,50.67,0.02,1990,Unfurnished,...,35,3,4,Low,No,Yes,"Clubhouse, Garden",East,Owner,Ready_to_Move
27,Punjab,Ludhiana,Locality_382,Independent House,4,4151,143.90,0.03,1995,Unfurnished,...,30,4,10,High,No,Yes,"Pool, Garden, Playground, Gym",West,Owner,Ready_to_Move
28,Maharashtra,Pune,Locality_143,Apartment,5,2346,404.23,0.17,2016,Semi-furnished,...,9,8,7,High,No,Yes,"Garden, Playground, Pool, Clubhouse",South,Owner,Ready_to_Move
29,Gujarat,Ahmedabad,Locality_74,Independent House,5,2088,233.29,0.11,1999,Unfurnished,...,26,1,2,Medium,Yes,Yes,"Pool, Garden",East,Owner,Ready_to_Move
30,Telangana,Hyderabad,Locality_454,Apartment,3,2750,59.35,0.02,2002,Furnished,...,23,6,8,Low,Yes,No,"Playground, Pool",West,Broker,Under_Construction

In [32]:
df.loc[(df.City == 'Mumbai') & (df.Nearby_Schools > 2)]

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
377,Maharashtra,Mumbai,Locality_132,Villa,5,1144,372.99,0.33,2003,Unfurnished,...,22,6,2,High,No,No,"Pool, Gym, Playground, Garden",South,Broker,Ready_to_Move
487,Maharashtra,Mumbai,Locality_276,Villa,1,1815,31.27,0.02,2005,Semi-furnished,...,20,7,7,Low,Yes,No,Garden,North,Builder,Ready_to_Move
589,Maharashtra,Mumbai,Locality_289,Villa,3,4945,210.14,0.04,2019,Semi-furnished,...,6,5,5,Medium,No,Yes,"Clubhouse, Playground, Gym, Garden",North,Broker,Under_Construction
620,Maharashtra,Mumbai,Locality_334,Villa,1,1167,220.74,0.19,2011,Unfurnished,...,14,3,6,Medium,No,Yes,"Playground, Pool, Clubhouse, Garden",East,Owner,Ready_to_Move
647,Maharashtra,Mumbai,Locality_291,Apartment,2,2271,326.97,0.14,2018,Unfurnished,...,7,7,4,Low,No,Yes,"Pool, Garden, Gym, Clubhouse",South,Owner,Ready_to_Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249640,Maharashtra,Mumbai,Locality_269,Apartment,4,4268,163.47,0.04,2013,Furnished,...,12,6,9,High,Yes,Yes,Clubhouse,North,Owner,Under_Construction
249643,Maharashtra,Mumbai,Locality_171,Apartment,5,3548,359.99,0.10,2002,Semi-furnished,...,23,3,3,Medium,Yes,No,"Playground, Pool, Gym, Garden, Clubhouse",East,Owner,Ready_to_Move
249696,Maharashtra,Mumbai,Locality_31,Villa,1,1894,167.74,0.09,2016,Unfurnished,...,9,9,5,Low,No,Yes,"Playground, Gym",East,Builder,Ready_to_Move
249873,Maharashtra,Mumbai,Locality_455,Villa,1,1052,228.34,0.22,2001,Semi-furnished,...,24,10,9,Medium,No,No,"Gym, Clubhouse, Playground, Garden, Pool",North,Builder,Ready_to_Move
249968,Maharashtra,Mumbai,Locality_261,Independent House,1,3543,167.78,0.05,2004,Furnished,...,21,3,6,Medium,Yes,Yes,"Garden, Playground",East,Owner,Ready_to_Move

In [22]:
(df.State == 'Gujarat').sum()

np.int64(12578)

In [24]:
counts = df['State'].value_counts()

State
Odisha            12681
Tamil Nadu        12629
West Bengal       12622
Gujarat           12578
Delhi             12552
Telangana         12539
Maharashtra       12533
Punjab            12516
Uttar Pradesh     12508
Uttarakhand       12501
Assam             12496
Kerala            12487
Jharkhand         12480
Andhra Pradesh    12462
Chhattisgarh      12456
Madhya Pradesh    12451
Karnataka         12424
Rajasthan         12402
Bihar             12369
Haryana           12314
Name: count, dtype: int64

In [27]:
df['State'].value_counts().min(),df['State'].value_counts().max()

(np.int64(12314), np.int64(12681))