In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [4]:
# Displaying the dataset
df = pd.read_csv("../dataset/india_housing_prices.csv",index_col="ID")

In [6]:
df_mumbai = df[df["City"] == "Mumbai"]
df_mumbai

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
377,Maharashtra,Mumbai,Locality_132,Villa,5,1144,372.99,0.33,2003,Unfurnished,...,22,6,2,High,No,No,"Pool, Gym, Playground, Garden",South,Broker,Ready_to_Move
487,Maharashtra,Mumbai,Locality_276,Villa,1,1815,31.27,0.02,2005,Semi-furnished,...,20,7,7,Low,Yes,No,Garden,North,Builder,Ready_to_Move
589,Maharashtra,Mumbai,Locality_289,Villa,3,4945,210.14,0.04,2019,Semi-furnished,...,6,5,5,Medium,No,Yes,"Clubhouse, Playground, Gym, Garden",North,Broker,Under_Construction
620,Maharashtra,Mumbai,Locality_334,Villa,1,1167,220.74,0.19,2011,Unfurnished,...,14,3,6,Medium,No,Yes,"Playground, Pool, Clubhouse, Garden",East,Owner,Ready_to_Move
647,Maharashtra,Mumbai,Locality_291,Apartment,2,2271,326.97,0.14,2018,Unfurnished,...,7,7,4,Low,No,Yes,"Pool, Garden, Gym, Clubhouse",South,Owner,Ready_to_Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249696,Maharashtra,Mumbai,Locality_31,Villa,1,1894,167.74,0.09,2016,Unfurnished,...,9,9,5,Low,No,Yes,"Playground, Gym",East,Builder,Ready_to_Move
249817,Maharashtra,Mumbai,Locality_310,Villa,2,1428,351.20,0.25,2000,Unfurnished,...,25,2,6,Low,No,No,Pool,East,Owner,Under_Construction
249873,Maharashtra,Mumbai,Locality_455,Villa,1,1052,228.34,0.22,2001,Semi-furnished,...,24,10,9,Medium,No,No,"Gym, Clubhouse, Playground, Garden, Pool",North,Builder,Ready_to_Move
249943,Maharashtra,Mumbai,Locality_245,Villa,3,4141,285.19,0.07,2023,Furnished,...,2,1,6,Medium,Yes,No,Garden,North,Builder,Under_Construction
249968,Maharashtra,Mumbai,Locality_261,Independent House,1,3543,167.78,0.05,2004,Furnished,...,21,3,6,Medium,Yes,Yes,"Garden, Playground",East,Owner,Ready_to_Move

In [7]:
df[df["BHK"] >= 3]

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move
6,West Bengal,Durgapur,Locality_246,Apartment,4,3500,135.28,0.04,2020,Semi-furnished,...,5,7,7,Low,Yes,Yes,"Playground, Clubhouse",West,Broker,Ready_to_Move
7,Tamil Nadu,Coimbatore,Locality_254,Independent House,3,4826,318.12,0.07,2016,Furnished,...,9,3,6,High,No,Yes,"Clubhouse, Garden, Playground",North,Builder,Under_Construction
8,Chhattisgarh,Bilaspur,Locality_490,Independent House,5,4252,141.39,0.03,2021,Unfurnished,...,4,10,10,High,Yes,Yes,"Gym, Pool, Clubhouse, Playground",North,Builder,Under_Construction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249994,Odisha,Cuttack,Locality_280,Independent House,5,4873,79.73,0.02,1992,Semi-furnished,...,33,10,8,Medium,No,Yes,"Clubhouse, Garden, Gym, Pool",North,Builder,Ready_to_Move
249995,Telangana,Warangal,Locality_313,Apartment,3,3020,97.98,0.03,2005,Furnished,...,20,5,4,Low,Yes,Yes,"Pool, Clubhouse, Garden",West,Builder,Under_Construction
249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,Furnished,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,Furnished,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,Semi-furnished,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [8]:
df[df["Price_in_Lakhs"] > 200]

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
7,Tamil Nadu,Coimbatore,Locality_254,Independent House,3,4826,318.12,0.07,2016,Furnished,...,9,3,6,High,No,Yes,"Clubhouse, Garden, Playground",North,Builder,Under_Construction
11,Telangana,Warangal,Locality_75,Independent House,1,665,324.24,0.49,1991,Semi-furnished,...,34,1,8,Low,No,Yes,Clubhouse,North,Broker,Under_Construction
12,Karnataka,Bangalore,Locality_462,Apartment,5,3988,465.38,0.12,2022,Furnished,...,3,6,4,High,No,Yes,"Clubhouse, Pool, Playground, Gym",West,Broker,Ready_to_Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249991,Jharkhand,Ranchi,Locality_403,Villa,3,1261,307.44,0.24,2019,Semi-furnished,...,6,10,9,Medium,Yes,No,"Clubhouse, Playground",East,Owner,Under_Construction
249992,Haryana,Faridabad,Locality_143,Independent House,3,3277,495.99,0.15,2009,Unfurnished,...,16,2,6,Low,Yes,Yes,"Garden, Gym, Clubhouse, Playground, Pool",South,Builder,Under_Construction
249993,Delhi,Dwarka,Locality_83,Apartment,1,3408,225.27,0.07,2003,Furnished,...,22,9,4,Low,Yes,Yes,"Pool, Playground, Gym, Garden, Clubhouse",East,Builder,Ready_to_Move
249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,Furnished,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,Furnished,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction

In [9]:
df[["BHK", "Size_in_SqFt", "Price_in_Lakhs"]]

        BHK  Size_in_SqFt  Price_in_Lakhs
ID
1         1          4740          489.76
2         3          2364          195.52
3         2          3642          183.79
4         2          2741          300.29
5         4          4823          182.90
...     ...           ...             ...
249996    5          1995          274.75
249997    1          2293           13.40
249998    4          2910          236.94
249999    1          1149          141.66
250000    3          4313          199.69

[250000 rows x 3 columns]

In [16]:
df[(df["State"] == "Delhi") & (df["BHK"] >= 4)]

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
9,Delhi,New Delhi,Locality_232,Villa,4,2678,189.16,0.07,2003,Semi-furnished,...,22,7,5,Low,No,Yes,"Garden, Clubhouse, Playground",South,Broker,Under_Construction
169,Delhi,New Delhi,Locality_353,Apartment,5,653,483.31,0.74,2006,Unfurnished,...,19,6,2,Low,Yes,No,"Clubhouse, Playground, Pool",East,Broker,Ready_to_Move
290,Delhi,Dwarka,Locality_398,Villa,4,4744,238.36,0.05,1991,Unfurnished,...,34,5,9,Medium,Yes,Yes,"Garden, Gym, Playground, Pool, Clubhouse",West,Builder,Under_Construction
292,Delhi,New Delhi,Locality_320,Independent House,4,4198,61.51,0.01,1999,Semi-furnished,...,26,3,10,High,Yes,Yes,"Garden, Clubhouse, Playground, Gym, Pool",West,Broker,Under_Construction
320,Delhi,New Delhi,Locality_351,Apartment,4,1864,45.58,0.02,1998,Unfurnished,...,27,6,9,High,Yes,No,"Playground, Gym, Clubhouse, Garden, Pool",East,Broker,Ready_to_Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249780,Delhi,Dwarka,Locality_79,Apartment,5,4241,177.14,0.04,1992,Unfurnished,...,33,8,5,Low,No,Yes,"Pool, Garden, Playground",North,Builder,Under_Construction
249811,Delhi,New Delhi,Locality_309,Independent House,5,1327,405.29,0.31,2006,Furnished,...,19,8,8,High,Yes,No,"Playground, Pool, Garden, Clubhouse, Gym",South,Broker,Ready_to_Move
249919,Delhi,New Delhi,Locality_357,Apartment,4,3559,198.14,0.06,1999,Semi-furnished,...,26,5,2,Medium,Yes,Yes,"Clubhouse, Gym",North,Owner,Under_Construction
249973,Delhi,New Delhi,Locality_176,Independent House,5,1644,341.21,0.21,2000,Semi-furnished,...,25,10,2,High,Yes,No,"Gym, Playground, Clubhouse",West,Builder,Under_Construction
249987,Delhi,Dwarka,Locality_127,Villa,5,3890,360.63,0.09,1996,Furnished,...,29,2,6,High,Yes,No,"Clubhouse, Pool, Playground",South,Broker,Ready_to_Move