In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [4]:
# Displaying the dataset
df = pd.read_csv("../dataset/india_housing_prices.csv",index_col="ID")
df.head()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [10]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = df.select_dtypes(include=["object"]).columns

numerical_cols = np.array(numerical_cols)

In [8]:
df.describe()

,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,2.999396,2749.813216,254.586854,0.130597,2006.520012,14.966800,15.503004,18.479988,5.499860,5.498016
std,1.415521,1300.606954,141.349921,0.130747,9.808575,8.948047,8.671618,9.808575,2.878639,2.871860
min,1.000000,500.000000,10.000000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000
25%,2.000000,1623.000000,132.550000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000
50%,3.000000,2747.000000,253.870000,0.090000,2007.000000,15.000000,15.000000,18.000000,5.000000,5.000000
75%,4.000000,3874.000000,376.880000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000
max,5.000000,5000.000000,500.000000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000

In [16]:
for i in numerical_cols:
    print(i,"(mean):",df[i].mean())

BHK (mean): 2.999396
Size_in_SqFt (mean): 2749.813216
Price_in_Lakhs (mean): 254.58685404
Price_per_SqFt (mean): 0.1305968
Year_Built (mean): 2006.520012
Floor_No (mean): 14.9668
Total_Floors (mean): 15.503004
Age_of_Property (mean): 18.479988
Nearby_Schools (mean): 5.49986
Nearby_Hospitals (mean): 5.498016

In [22]:
# A much easier way
mean_summary = df[numerical_cols].mean()
print(mean_summary)

BHK                    2.999396
Size_in_SqFt        2749.813216
Price_in_Lakhs       254.586854
Price_per_SqFt         0.130597
Year_Built          2006.520012
Floor_No              14.966800
Total_Floors          15.503004
Age_of_Property       18.479988
Nearby_Schools         5.499860
Nearby_Hospitals       5.498016
dtype: float64

In [23]:
for col in categorical_cols:
    print(f"{col}")
    print(df[col].value_counts())
    print("\n")

State
State
Odisha            12681
Tamil Nadu        12629
West Bengal       12622
Gujarat           12578
Delhi             12552
Telangana         12539
Maharashtra       12533
Punjab            12516
Uttar Pradesh     12508
Uttarakhand       12501
Assam             12496
Kerala            12487
Jharkhand         12480
Andhra Pradesh    12462
Chhattisgarh      12456
Madhya Pradesh    12451
Karnataka         12424
Rajasthan         12402
Bihar             12369
Haryana           12314
Name: count, dtype: int64


City
City
Coimbatore        6461
Ahmedabad         6411
Silchar           6404
Durgapur          6387
Cuttack           6358
Vijayawada        6344
Jamshedpur        6335
Bhubaneswar       6323
New Delhi         6306
Kochi             6305
Ludhiana          6295
Bhopal            6284
Hyderabad         6273
Noida             6271
Haridwar          6267
Warangal          6266
Bilaspur          6263
Dwarka            6246
Lucknow           6237
Kolkata           6235
Dehradun          6234
Jaipur            6231
Amritsar          6221
Patna             6199
Raipur            6193
Trivandrum        6182
Jodhpur           6171
Gaya              6170
Faridabad         6169
Chennai           6168
Surat             6167
Indore            6167
Gurgaon           6145
Ranchi            6145
Vishakhapatnam    6118
Guwahati          6092
Pune              4224
Mysore            4217
Nagpur            4160
Mumbai            4149
Bangalore         4144
Mangalore         4063
Name: count, dtype: int64


Locality
Locality
Locality_296    567
Locality_316    562
Locality_297    561
Locality_313    560
Locality_321    558
               ...
Locality_82     447
Locality_411    446
Locality_144    443
Locality_266    443
Locality_130    441
Name: count, Length: 500, dtype: int64


Property_Type
Property_Type
Villa                83744
Independent House    83300
Apartment            82956
Name: count, dtype: int64


Furnished_Status
Furnished_Status
Unfurnished       83408
Semi-furnished    83374
Furnished         83218
Name: count, dtype: int64


Public_Transport_Accessibility
Public_Transport_Accessibility
High      83705
Low       83287
Medium    83008
Name: count, dtype: int64


Parking_Space
Parking_Space
No     125456
Yes    124544
Name: count, dtype: int64


Security
Security
Yes    125233
No     124767
Name: count, dtype: int64


Amenities
Amenities
Pool                                        10218
Clubhouse                                   10010
Garden                                      10006
Gym                                          9938
Playground                                   9934
                                            ...
Playground, Gym, Clubhouse, Garden, Pool      369
Garden, Gym, Pool, Playground                 368
Pool, Garden, Clubhouse, Playground, Gym      367
Garden, Clubhouse, Pool, Gym                  360
Clubhouse, Pool, Garden, Playground, Gym      355
Name: count, Length: 325, dtype: int64


Facing
Facing
West     62757
North    62637
South    62337
East     62269
Name: count, dtype: int64


Owner_Type
Owner_Type
Broker     83479
Owner      83268
Builder    83253
Name: count, dtype: int64


Availability_Status
Availability_Status
Under_Construction    125035
Ready_to_Move         124965
Name: count, dtype: int64

## Maps

In [25]:
# Prices in Lakhs
df.Price_in_Lakhs.map(lambda p: p*100000)

ID
1         48976000.0
2         19552000.0
3         18379000.0
4         30029000.0
5         18290000.0
             ...
249996    27475000.0
249997     1340000.0
249998    23694000.0
249999    14166000.0
250000    19969000.0
Name: Price_in_Lakhs, Length: 250000, dtype: float64

In [26]:
df_Price_in_Lakhs = df.Price_in_Lakhs.mean()
df.Price_in_Lakhs.map(lambda p: p-df_Price_in_Lakhs)

ID
1         235.173146
2         -59.066854
3         -70.796854
4          45.703146
5         -71.686854
             ...
249996     20.163146
249997   -241.186854
249998    -17.646854
249999   -112.926854
250000    -54.896854
Name: Price_in_Lakhs, Length: 250000, dtype: float64

In [30]:
# Alternative: Apply

def deviation(row):
    row.Price_in_Lakhs = row.Price_in_Lakhs - df_Price_in_Lakhs
    return row
new_df = df.apply(deviation,axis = 'columns')
new_df

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,235.173146,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
2,Maharashtra,Pune,Locality_490,Independent House,3,2364,-59.066854,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,-70.796854,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,45.703146,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,-71.686854,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,20.163146,0.14,1995,Furnished,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,-241.186854,0.01,2013,Semi-furnished,...,12,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move
249998,Telangana,Warangal,Locality_225,Villa,4,2910,-17.646854,0.08,2003,Furnished,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
249999,Odisha,Cuttack,Locality_138,Villa,1,1149,-112.926854,0.12,2007,Unfurnished,...,18,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move
250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,-54.896854,0.05,1990,Semi-furnished,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [47]:
city_stats = {}
for i in df['City'].unique():
    i_mean = df[df['City'] == i]['Price_in_Lakhs'].mean()
    city_stats[i] = i_mean