In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [7]:
# Displaying the dataset
df = pd.read_csv("../dataset/india_housing_prices.csv",index_col="ID")
df.tail()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,Furnished,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,13.40,0.01,2013,Semi-furnished,...,12,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move
249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,Furnished,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
249999,Odisha,Cuttack,Locality_138,Villa,1,1149,141.66,0.12,2007,Unfurnished,...,18,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move
250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,Semi-furnished,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [3]:
df.groupby("City")["Price_in_Lakhs"].mean().sort_values(ascending=False)

City
Bangalore         258.456639
Surat             258.080467
Kochi             257.415221
Gaya              257.053391
Mangalore         256.920925
Dehradun          256.890115
Mysore            256.848172
Chennai           256.830172
Hyderabad         256.594051
Coimbatore        256.504745
Bhopal            256.498896
Pune              256.495661
Noida             256.287206
Lucknow           256.212431
Vishakhapatnam    255.772442
Nagpur            255.532012
Indore            255.413825
Jaipur            255.246241
Bhubaneswar       254.902173
Faridabad         254.862393
Vijayawada        254.643766
Ranchi            254.624529
Warangal          254.475113
Durgapur          254.100152
Gurgaon           254.027549
Jodhpur           253.947906
Kolkata           253.914897
Ahmedabad         253.586827
Raipur            253.482416
Dwarka            253.454299
Ludhiana          253.159636
Guwahati          252.992710
Patna             252.794673
Jamshedpur        252.626185
Silchar           252.576160
Haridwar          252.476004
Amritsar          252.429802
Mumbai            252.056633
Bilaspur          251.879267
New Delhi         251.614296
Trivandrum        251.258801
Cuttack           250.786672
Name: Price_in_Lakhs, dtype: float64

In [4]:
df.groupby("BHK")["Price_in_Lakhs"].mean()

BHK
1    254.875273
2    254.795333
3    254.088449
4    254.784919
5    254.391967
Name: Price_in_Lakhs, dtype: float64

In [5]:
df.groupby("Property_Type")["Price_in_Lakhs"].agg(["mean","median","count"])

                         mean   median  count
Property_Type
Apartment          254.622116  254.020  82956
Independent House  255.374150  255.040  83300
Villa              253.768802  252.535  83744

In [6]:
df["Amenity_Count"] = df["Amenities"].apply(lambda x: len(x.split(",")))
df.groupby("Amenity_Count")["Price_in_Lakhs"].mean()

Amenity_Count
1    254.751700
2    253.968325
3    254.627492
4    254.664747
5    254.919710
Name: Price_in_Lakhs, dtype: float64

In [9]:
cols = [
    "Price_in_Lakhs",
    "Size_in_SqFt",
    "BHK",
    "Age_of_Property",
    "Floor_No",
    "Total_Floors",
    "Nearby_Schools",
    "Nearby_Hospitals"
]
df[cols].agg(["min", "max"])

,Price_in_Lakhs,Size_in_SqFt,BHK,Age_of_Property,Floor_No,Total_Floors,Nearby_Schools,Nearby_Hospitals
min,10.0,500,1,2,0,1,1,1
max,500.0,5000,5,35,30,30,10,10

In [14]:
df.loc[df["Price_in_Lakhs"].idxmax()]

State                                 Rajasthan
City                                    Jodhpur
Locality                            Locality_44
Property_Type                             Villa
BHK                                           4
Size_in_SqFt                               1950
Price_in_Lakhs                            500.0
Price_per_SqFt                             0.26
Year_Built                                 1997
Furnished_Status                      Furnished
Floor_No                                     19
Total_Floors                                 24
Age_of_Property                              28
Nearby_Schools                                6
Nearby_Hospitals                              7
Public_Transport_Accessibility           Medium
Parking_Space                                No
Security                                    Yes
Amenities                          Garden, Pool
Facing                                    North
Owner_Type                                Owner
Availability_Status               Ready_to_Move
Name: 7358, dtype: object

In [12]:
df.loc[df["Price_in_Lakhs"].idxmin()]

State                                        Haryana
City                                         Gurgaon
Locality                                 Locality_87
Property_Type                                  Villa
BHK                                                1
Size_in_SqFt                                    2346
Price_in_Lakhs                                  10.0
Price_per_SqFt                                   0.0
Year_Built                                      2023
Furnished_Status                      Semi-furnished
Floor_No                                          25
Total_Floors                                      16
Age_of_Property                                    2
Nearby_Schools                                     5
Nearby_Hospitals                                   5
Public_Transport_Accessibility                  High
Parking_Space                                     No
Security                                          No
Amenities                                 Playground
Facing                                         North
Owner_Type                                     Owner
Availability_Status               Under_Construction
Name: 133879, dtype: object