In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
# Displaying the dataset
df = pd.read_csv("../dataset/india_housing_prices.csv",index_col="ID")
df.tail()

,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
249996,Gujarat,Ahmedabad,Locality_187,Independent House,5,1995,274.75,0.14,1995,Furnished,...,30,8,6,Low,No,No,"Playground, Garden, Gym, Clubhouse, Pool",East,Broker,Under_Construction
249997,Tamil Nadu,Chennai,Locality_348,Apartment,1,2293,13.40,0.01,2013,Semi-furnished,...,12,8,10,Low,No,No,Playground,South,Broker,Ready_to_Move
249998,Telangana,Warangal,Locality_225,Villa,4,2910,236.94,0.08,2003,Furnished,...,22,10,4,High,Yes,Yes,Playground,South,Builder,Under_Construction
249999,Odisha,Cuttack,Locality_138,Villa,1,1149,141.66,0.12,2007,Unfurnished,...,18,3,7,Low,Yes,Yes,"Playground, Gym, Pool",South,Owner,Ready_to_Move
250000,Haryana,Gurgaon,Locality_268,Independent House,3,4313,199.69,0.05,1990,Semi-furnished,...,35,10,6,Medium,No,No,"Gym, Garden",South,Owner,Under_Construction

In [3]:
df_renamed = df.rename(columns={
    "Price_in_Lakhs": "Price_Lakhs",
    "Size_in_SqFt": "Area_SqFt",
    "BHK": "Bedrooms",
    "Floor_No": "Floor_Number"
})

df_renamed.head()

,State,City,Locality,Property_Type,Bedrooms,Area_SqFt,Price_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
ID,,,,,,,,,,,,,,,,,,,,,
1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [4]:
df_renamed = df_renamed.rename_axis("Property_ID", axis="rows")
df_renamed = df_renamed.rename_axis("Features", axis="columns")

df_renamed.head()

Features,State,City,Locality,Property_Type,Bedrooms,Area_SqFt,Price_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
Property_ID,,,,,,,,,,,,,,,,,,,,,
1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,Furnished,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,Semi-furnished,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,Furnished,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [9]:
mumbai = df[df["City"] == "Mumbai"]
delhi = df[df["City"] == "Delhi"]

In [6]:
combined_df = pd.concat([mumbai, delhi])
combined_df.shape

(4149, 22)

In [10]:
price_col = df[["Price_in_Lakhs"]]
size_col = df[["Size_in_SqFt"]]

combined_horizontal = pd.concat([price_col, size_col], axis=1)
combined_horizontal.head()

    Price_in_Lakhs  Size_in_SqFt
ID
1           489.76          4740
2           195.52          2364
3           183.79          3642
4           300.29          2741
5           182.90          4823

In [11]:
city_avg_price = df.groupby("City")["Price_in_Lakhs"].mean()
city_avg_price = city_avg_price.to_frame(name="City_Avg_Price")
city_avg_price.head()

             City_Avg_Price
City
Ahmedabad        253.586827
Amritsar         252.429802
Bangalore        258.456639
Bhopal           256.498896
Bhubaneswar      254.902173

In [12]:
df_city_index = df.set_index("City")

In [13]:
df_joined = df_city_index.join(city_avg_price)
df_joined.head()

,State,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Furnished_Status,Floor_No,...,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status,City_Avg_Price
City,,,,,,,,,,,,,,,,,,,,,
Chennai,Tamil Nadu,Locality_84,Apartment,1,4740,489.76,0.10,1990,Furnished,22,...,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,256.830172
Pune,Maharashtra,Locality_490,Independent House,3,2364,195.52,0.08,2008,Unfurnished,21,...,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,256.495661
Ludhiana,Punjab,Locality_167,Apartment,2,3642,183.79,0.05,1997,Semi-furnished,19,...,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,253.159636
Jodhpur,Rajasthan,Locality_393,Independent House,2,2741,300.29,0.11,1991,Furnished,21,...,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,253.947906
Jaipur,Rajasthan,Locality_466,Villa,4,4823,182.90,0.04,2002,Semi-furnished,3,...,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,255.246241