In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [9]:
# Displaying the dataset
df_transformed_scaled = pd.read_csv("../dataset/df_transformed.csv")
df_transformed_scaled.tail()

,BHK,Size_in_SqFt,Price_in_Lakhs,Floor_No,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Locality_freq,Amenity_Count,Property_Type_Apartment,...,Property_Type_Villa,Owner_Type_Broker,Owner_Type_Builder,Owner_Type_Owner,Facing_East,Facing_North,Facing_South,Facing_West,State_TE,City_TE
249995,5,1995,274.75,19,30,8,6,520,5,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,255.250891,252.843885
249996,1,2293,13.40,15,12,8,10,490,1,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,257.768030,256.942195
249997,4,2910,236.94,21,22,10,4,518,1,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,254.960988,254.453728
249998,1,1149,141.66,14,18,3,7,472,3,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,252.270473,250.231555
249999,3,4313,199.69,22,35,10,6,496,2,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,254.065698,255.250880

In [10]:
numerical_cols = df_transformed_scaled.select_dtypes(include=["int64", "float64"]).columns
numerical_cols

Index(['BHK', 'Size_in_SqFt', 'Price_in_Lakhs', 'Floor_No', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Locality_freq', 'Amenity_Count',
       'Property_Type_Apartment', 'Property_Type_Independent House',
       'Property_Type_Villa', 'Owner_Type_Broker', 'Owner_Type_Builder',
       'Owner_Type_Owner', 'Facing_East', 'Facing_North', 'Facing_South',
       'Facing_West', 'State_TE', 'City_TE'],
      dtype='str')

In [14]:
num_cols_to_scale = [
    "BHK",
    "Size_in_SqFt",
    "Floor_No",
    "Age_of_Property",
    "Nearby_Schools",
    "Nearby_Hospitals",
    "Amenity_Count",
    "State_TE",
    "City_TE",
    "Locality_freq"
]

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_transformed_scaled[num_cols_to_scale] = scaler.fit_transform(df_transformed_scaled[num_cols_to_scale])

In [16]:
df_transformed_scaled

,BHK,Size_in_SqFt,Price_in_Lakhs,Floor_No,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Locality_freq,Amenity_Count,Property_Type_Apartment,...,Property_Type_Villa,Owner_Type_Broker,Owner_Type_Builder,Owner_Type_Owner,Facing_East,Facing_North,Facing_South,Facing_West,State_TE,City_TE
0,-1.412483,1.530202,489.76,0.786006,1.684245,1.563291,-0.869827,-0.755308,1.413942,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.361881,1.219000
1,0.000427,-0.296641,195.52,0.674249,-0.150887,0.868516,-1.566241,0.620627,1.413942,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-0.605087,0.304747
2,-0.706028,0.685979,183.79,0.450736,0.970582,1.215904,0.871208,0.398702,0.706869,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.617930,-0.945949
3,-0.706028,-0.006776,300.29,0.674249,1.582293,-0.173645,0.523001,1.242017,1.413942,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,-0.338037,-0.972159
4,0.706882,1.594018,182.90,-1.337367,0.460823,-0.521032,1.219416,0.487472,1.413942,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.561636,0.771379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1.413337,-0.580356,274.75,0.450736,1.174486,0.868516,0.174794,0.842552,1.413942,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.431547,-0.803150
249996,-1.412483,-0.351231,13.40,0.003710,-0.660646,0.868516,1.567623,-0.488998,-1.414349,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,2.068489,1.083263
249997,0.706882,0.123163,236.94,0.674249,0.358872,1.563291,-0.521620,0.753782,-1.414349,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.243017,-0.062155
249998,-1.412483,-1.230823,141.66,-0.108046,-0.048936,-0.868419,0.523001,-1.287928,-0.000204,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.506674,-2.005581
249999,0.000427,1.201893,199.69,0.786006,1.684245,1.563291,0.174794,-0.222688,-0.707276,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.339206,0.304767

In [18]:
df_transformed_scaled.to_csv("../dataset/df_transformed_scalar.csv", index=False)