In [2]:
import pandas as pd
df = pd.read_csv("/content/dataset.csv")
df.head()

,area,building_type,building_nature,num_bath_rooms,num_bed_rooms,price,property_url,purpose,city,locality,...,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,division,zone,price_per_sqft
0,2464.0,Apartment,Residential,4.0,3.0,28900000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Dhanmondi,...,1,2,1,1,3,3,4,Dhaka,Dhanmondi,11728.896104
1,1920.0,Apartment,Residential,3.0,3.0,20000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Bashundhara R-A,...,1,1,2,1,3,2,3,Dhaka,Bashundhara R/A,10416.666667
2,1445.0,Apartment,Residential,3.0,3.0,10800000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Banasree,...,1,2,2,1,1,3,4,Dhaka,Khilgaon,7474.048443
3,1475.0,Apartment,Residential,3.0,3.0,10500000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Uttara,...,1,2,3,1,3,3,4,Dhaka,Uttara,7118.644068
4,1066.0,Apartment,Residential,2.0,3.0,8000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Sutrapur,...,1,1,2,1,4,3,4,Dhaka,Sutrapur,7504.690432

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18754 entries, 0 to 18753
Data columns (total 22 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   area                                   18754 non-null  float64
 1   building_type                          18754 non-null  object
 2   building_nature                        18754 non-null  object
 3   num_bath_rooms                         18754 non-null  float64
 4   num_bed_rooms                          18754 non-null  float64
 5   price                                  18754 non-null  float64
 6   property_url                           18754 non-null  object
 7   purpose                                18754 non-null  object
 8   city                                   18754 non-null  object
 9   locality                               18754 non-null  object
 10  address                                18754 non-null  object
 11  id                                     18754 non-null  object
 12  relaxation_amenity_count               18754 non-null  int64
 13  security_amenity_count                 18754 non-null  int64
 14  maintenance_or_cleaning_amenity_count  18754 non-null  int64
 15  social_amenity_count                   18754 non-null  int64
 16  expendable_amenity_count               18754 non-null  int64
 17  service_staff_amenity_count            18754 non-null  int64
 18  unclassify_amenity_count               18754 non-null  int64
 19  division                               18754 non-null  object
 20  zone                                   18754 non-null  object
 21  price_per_sqft                         18754 non-null  float64
dtypes: float64(5), int64(7), object(10)
memory usage: 3.1+ MB

In [5]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns
print("Numerical Columns:")
print(num_cols)
print("\nCategorical Columns:")
print(cat_cols)

Numerical Columns:
Index(['area', 'num_bath_rooms', 'num_bed_rooms', 'price',
       'relaxation_amenity_count', 'security_amenity_count',
       'maintenance_or_cleaning_amenity_count', 'social_amenity_count',
       'expendable_amenity_count', 'service_staff_amenity_count',
       'unclassify_amenity_count', 'price_per_sqft'],
      dtype='object')

Categorical Columns:
Index(['building_type', 'building_nature', 'property_url', 'purpose', 'city',
       'locality', 'address', 'id', 'division', 'zone'],
      dtype='object')

In [7]:
amenity_cols = [
    "relaxation_amenity_count",
    "security_amenity_count",
    "maintenance_or_cleaning_amenity_count",
    "social_amenity_count",
    "expendable_amenity_count",
    "service_staff_amenity_count",
    "unclassify_amenity_count"
]

df["total_amenity_count"] = df[amenity_cols].sum(axis=1)

In [8]:
df["total_amenity_count"].head()

0    15
1    13
2    14
3    17
4    16
Name: total_amenity_count, dtype: int64

In [9]:
df.drop(["property_url", "id", "address"], axis=1, inplace=True)

In [10]:
print(df.isnull().sum())

area                                     0
building_type                            0
building_nature                          0
num_bath_rooms                           0
num_bed_rooms                            0
price                                    0
purpose                                  0
city                                     0
locality                                 0
relaxation_amenity_count                 0
security_amenity_count                   0
maintenance_or_cleaning_amenity_count    0
social_amenity_count                     0
expendable_amenity_count                 0
service_staff_amenity_count              0
unclassify_amenity_count                 0
division                                 0
zone                                     0
price_per_sqft                           0
total_amenity_count                      0
dtype: int64

In [11]:
df = pd.get_dummies(df, columns=["city"], drop_first=True)

In [12]:
print(df.columns)

Index(['area', 'building_type', 'building_nature', 'num_bath_rooms',
       'num_bed_rooms', 'price', 'purpose', 'locality',
       'relaxation_amenity_count', 'security_amenity_count',
       'maintenance_or_cleaning_amenity_count', 'social_amenity_count',
       'expendable_amenity_count', 'service_staff_amenity_count',
       'unclassify_amenity_count', 'division', 'zone', 'price_per_sqft',
       'total_amenity_count', 'city_Barguna', 'city_Barishal', 'city_Bogura',
       'city_Brahmanbaria', 'city_Chandpur', 'city_Chattogram',
       'city_Chittagong', 'city_Cumilla', 'city_Dhaka', 'city_Dinajpur',
       'city_Gaibandha', 'city_Gazipur', 'city_Gopalganj', 'city_Habiganj',
       'city_Jashore', 'city_Khulna', 'city_Kishoreganj', 'city_Kushtia',
       'city_Lakshmipur', 'city_Madaripur', 'city_Magura', 'city_Manikganj',
       'city_Mymensingh', 'city_Naogaon', 'city_Narayanganj',
       'city_Narayanganj City', 'city_Narsingdi', 'city_Nilphamari',
       'city_Rajshahi', 'city_Rangpur', 'city_Shariatpur', 'city_Sherpur',
       'city_Sirajganj', 'city_Sylhet', 'city_Tangail', 'city_Thakurgaon'],
      dtype='object')

In [13]:
print('city' in df.columns)

False

In [14]:
city_cols = [col for col in df.columns if col.startswith("city_")]

df[city_cols] = df[city_cols].astype(int)
print(df[city_cols].head())

   city_Barguna  city_Barishal  city_Bogura  city_Brahmanbaria  city_Chandpur  \
0             0              0            0                  0              0
1             0              0            0                  0              0
2             0              0            0                  0              0
3             0              0            0                  0              0
4             0              0            0                  0              0

   city_Chattogram  city_Chittagong  city_Cumilla  city_Dhaka  city_Dinajpur  \
0                0                0             0           1              0
1                0                0             0           1              0
2                0                0             0           1              0
3                0                0             0           1              0
4                0                0             0           1              0

   ...  city_Narsingdi  city_Nilphamari  city_Rajshahi  city_Rangpur  \
0  ...               0                0              0             0
1  ...               0                0              0             0
2  ...               0                0              0             0
3  ...               0                0              0             0
4  ...               0                0              0             0

   city_Shariatpur  city_Sherpur  city_Sirajganj  city_Sylhet  city_Tangail  \
0                0             0               0            0             0
1                0             0               0            0             0
2                0             0               0            0             0
3                0             0               0            0             0
4                0             0               0            0             0

   city_Thakurgaon
0                0
1                0
2                0
3                0
4                0

[5 rows x 36 columns]

In [17]:
location_mean = df.groupby("locality")["price"].mean()
df["locality_encoded"] = df["locality"].map(location_mean)
print(df[["locality", "locality_encoded"]].head())

          locality  locality_encoded
0        Dhanmondi      2.298431e+06
1  Bashundhara R-A      1.189725e+07
2         Banasree      8.523449e+06
3           Uttara      7.475096e+06
4         Sutrapur      2.970743e+06

In [18]:
print(df["area"].dtype)

float64

In [19]:
df["area"] = pd.to_numeric(df["area"], errors="coerce")

In [20]:
df["area"] = df["area"].astype(str).str.extract(r"(\d+)").astype(float)

In [21]:
print(df.head())
print(df.dtypes)

     area building_type building_nature  num_bath_rooms  num_bed_rooms  \
0  2464.0     Apartment     Residential             4.0            3.0
1  1920.0     Apartment     Residential             3.0            3.0
2  1445.0     Apartment     Residential             3.0            3.0
3  1475.0     Apartment     Residential             3.0            3.0
4  1066.0     Apartment     Residential             2.0            3.0

        price purpose         locality  relaxation_amenity_count  \
0  28900000.0    Sale        Dhanmondi                         1
1  20000000.0    Sale  Bashundhara R-A                         1
2  10800000.0    Sale         Banasree                         1
3  10500000.0    Sale           Uttara                         1
4   8000000.0    Sale         Sutrapur                         1

   security_amenity_count  ...  city_Nilphamari  city_Rajshahi  city_Rangpur  \
0                       2  ...                0              0             0
1                       1  ...                0              0             0
2                       2  ...                0              0             0
3                       2  ...                0              0             0
4                       1  ...                0              0             0

   city_Shariatpur  city_Sherpur city_Sirajganj city_Sylhet  city_Tangail  \
0                0             0              0           0             0
1                0             0              0           0             0
2                0             0              0           0             0
3                0             0              0           0             0
4                0             0              0           0             0

   city_Thakurgaon  locality_encoded
0                0      2.298431e+06
1                0      1.189725e+07
2                0      8.523449e+06
3                0      7.475096e+06
4                0      2.970743e+06

[5 rows x 56 columns]
area                                     float64
building_type                             object
building_nature                           object
num_bath_rooms                           float64
num_bed_rooms                            float64
price                                    float64
purpose                                   object
locality                                  object
relaxation_amenity_count                   int64
security_amenity_count                     int64
maintenance_or_cleaning_amenity_count      int64
social_amenity_count                       int64
expendable_amenity_count                   int64
service_staff_amenity_count                int64
unclassify_amenity_count                   int64
division                                  object
zone                                      object
price_per_sqft                           float64
total_amenity_count                        int64
city_Barguna                               int64
city_Barishal                              int64
city_Bogura                                int64
city_Brahmanbaria                          int64
city_Chandpur                              int64
city_Chattogram                            int64
city_Chittagong                            int64
city_Cumilla                               int64
city_Dhaka                                 int64
city_Dinajpur                              int64
city_Gaibandha                             int64
city_Gazipur                               int64
city_Gopalganj                             int64
city_Habiganj                              int64
city_Jashore                               int64
city_Khulna                                int64
city_Kishoreganj                           int64
city_Kushtia                               int64
city_Lakshmipur                            int64
city_Madaripur                             int64
city_Magura                                int64
city_Manikganj                             int64
city_Mymensingh                            int64
city_Naogaon                               int64
city_Narayanganj                           int64
city_Narayanganj City                      int64
city_Narsingdi                             int64
city_Nilphamari                            int64
city_Rajshahi                              int64
city_Rangpur                               int64
city_Shariatpur                            int64
city_Sherpur                               int64
city_Sirajganj                             int64
city_Sylhet                                int64
city_Tangail                               int64
city_Thakurgaon                            int64
locality_encoded                         float64
dtype: object