In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [5]:
df = pd.read_csv("../dataset/dataset.csv")

In [6]:
df.head()

,area,building_type,building_nature,num_bath_rooms,num_bed_rooms,price,property_url,purpose,city,locality,...,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,division,zone,price_per_sqft
0,2464.0,Apartment,Residential,4.0,3.0,28900000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Dhanmondi,...,1,2,1,1,3,3,4,Dhaka,Dhanmondi,11728.896104
1,1920.0,Apartment,Residential,3.0,3.0,20000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Bashundhara R-A,...,1,1,2,1,3,2,3,Dhaka,Bashundhara R/A,10416.666667
2,1445.0,Apartment,Residential,3.0,3.0,10800000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Banasree,...,1,2,2,1,1,3,4,Dhaka,Khilgaon,7474.048443
3,1475.0,Apartment,Residential,3.0,3.0,10500000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Uttara,...,1,2,3,1,3,3,4,Dhaka,Uttara,7118.644068
4,1066.0,Apartment,Residential,2.0,3.0,8000000.0,https://www.bproperty.com/en/property/details-...,Sale,Dhaka,Sutrapur,...,1,1,2,1,4,3,4,Dhaka,Sutrapur,7504.690432

In [7]:
df.tail()

,area,building_type,building_nature,num_bath_rooms,num_bed_rooms,price,property_url,purpose,city,locality,...,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,division,zone,price_per_sqft
18749,375.0,Apartment,Residential,1.0,1.0,3600000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,...,1,1,2,3,4,2,13,Dhaka,Bashundhara R/A,9600.00
18750,375.0,Apartment,Residential,1.0,1.0,3600000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,...,1,2,1,1,4,2,1,Dhaka,Bashundhara R/A,9600.00
18751,800.0,Apartment,Residential,2.0,2.0,4800000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,...,1,1,2,1,3,3,1,Dhaka,Bashundhara R/A,6000.00
18752,800.0,Apartment,Residential,2.0,2.0,4800000.0,https://www.thetolet.com/en/dhaka/bashundhara-...,Rent,Dhaka,Bashundhara R.A,...,1,1,1,1,1,2,1,Dhaka,Bashundhara R/A,6000.00
18753,1600.0,Office,Commercial,3.0,3.0,2850000.0,https://www.thetolet.com/en/dhaka/adabor/31021...,Rent,Dhaka,Adabor,...,1,2,2,1,1,2,1,Dhaka,Mohammadpur,1781.25

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18754 entries, 0 to 18753
Data columns (total 22 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   area                                   18754 non-null  float64
 1   building_type                          18754 non-null  str
 2   building_nature                        18754 non-null  str
 3   num_bath_rooms                         18754 non-null  float64
 4   num_bed_rooms                          18754 non-null  float64
 5   price                                  18754 non-null  float64
 6   property_url                           18754 non-null  str
 7   purpose                                18754 non-null  str
 8   city                                   18754 non-null  str
 9   locality                               18754 non-null  str
 10  address                                18754 non-null  str
 11  id                                     18754 non-null  str
 12  relaxation_amenity_count               18754 non-null  int64
 13  security_amenity_count                 18754 non-null  int64
 14  maintenance_or_cleaning_amenity_count  18754 non-null  int64
 15  social_amenity_count                   18754 non-null  int64
 16  expendable_amenity_count               18754 non-null  int64
 17  service_staff_amenity_count            18754 non-null  int64
 18  unclassify_amenity_count               18754 non-null  int64
 19  division                               18754 non-null  str
 20  zone                                   18754 non-null  str
 21  price_per_sqft                         18754 non-null  float64
dtypes: float64(5), int64(7), str(10)
memory usage: 3.1 MB

In [9]:
numeric_df = df.select_dtypes(include=["int64", "float64"])
print("Numeric Columns:")
print(numeric_df.columns)

Numeric Columns:
Index(['area', 'num_bath_rooms', 'num_bed_rooms', 'price',
       'relaxation_amenity_count', 'security_amenity_count',
       'maintenance_or_cleaning_amenity_count', 'social_amenity_count',
       'expendable_amenity_count', 'service_staff_amenity_count',
       'unclassify_amenity_count', 'price_per_sqft'],
      dtype='str')

In [10]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(numeric_df)
scaled_df = pd.DataFrame(scaled_data, columns=numeric_df.columns)

In [11]:
scaled_df.head()

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,price_per_sqft
0,0.000205,0.061224,0.036364,0.013920,0.0,0.25,0.0,0.0,0.4,0.666667,0.176471,0.970168
1,0.000160,0.040816,0.036364,0.009633,0.0,0.00,0.5,0.0,0.4,0.333333,0.117647,0.861626
2,0.000120,0.040816,0.036364,0.005202,0.0,0.25,0.5,0.0,0.0,0.666667,0.176471,0.618224
3,0.000123,0.040816,0.036364,0.005057,0.0,0.25,1.0,0.0,0.4,0.666667,0.176471,0.588826
4,0.000089,0.020408,0.036364,0.003853,0.0,0.00,0.5,0.0,0.6,0.666667,0.176471,0.620758

In [12]:
scaled_df

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,price_per_sqft
0,0.000205,0.061224,0.036364,0.013920,0.0,0.25,0.0,0.0,0.4,0.666667,0.176471,0.970168
1,0.000160,0.040816,0.036364,0.009633,0.0,0.00,0.5,0.0,0.4,0.333333,0.117647,0.861626
2,0.000120,0.040816,0.036364,0.005202,0.0,0.25,0.5,0.0,0.0,0.666667,0.176471,0.618224
3,0.000123,0.040816,0.036364,0.005057,0.0,0.25,1.0,0.0,0.4,0.666667,0.176471,0.588826
4,0.000089,0.020408,0.036364,0.003853,0.0,0.00,0.5,0.0,0.6,0.666667,0.176471,0.620758
...,...,...,...,...,...,...,...,...,...,...,...,...
18749,0.000031,0.000000,0.000000,0.001734,0.0,0.00,0.5,0.5,0.6,0.333333,0.705882,0.794074
18750,0.000031,0.000000,0.000000,0.001734,0.0,0.25,0.0,0.0,0.6,0.333333,0.000000,0.794074
18751,0.000067,0.020408,0.018182,0.002312,0.0,0.00,0.5,0.0,0.4,0.666667,0.000000,0.496296
18752,0.000067,0.020408,0.018182,0.002312,0.0,0.00,0.0,0.0,0.0,0.333333,0.000000,0.496296
18753,0.000133,0.040816,0.036364,0.001373,0.0,0.25,0.5,0.0,0.0,0.333333,0.000000,0.147338

In [14]:
manual_scaled = (numeric_df - numeric_df.min()) / (numeric_df.max() - numeric_df.min())

In [16]:
manual_scaled.head()

,area,num_bath_rooms,num_bed_rooms,price,relaxation_amenity_count,security_amenity_count,maintenance_or_cleaning_amenity_count,social_amenity_count,expendable_amenity_count,service_staff_amenity_count,unclassify_amenity_count,price_per_sqft
0,0.000205,0.061224,0.036364,0.013920,0.0,0.25,0.0,0.0,0.4,0.666667,0.176471,0.970168
1,0.000160,0.040816,0.036364,0.009633,0.0,0.00,0.5,0.0,0.4,0.333333,0.117647,0.861626
2,0.000120,0.040816,0.036364,0.005202,0.0,0.25,0.5,0.0,0.0,0.666667,0.176471,0.618224
3,0.000123,0.040816,0.036364,0.005057,0.0,0.25,1.0,0.0,0.4,0.666667,0.176471,0.588826
4,0.000089,0.020408,0.036364,0.003853,0.0,0.00,0.5,0.0,0.6,0.666667,0.176471,0.620758