In [4]:
#Import Library
import pandas as pd

In [5]:
#Load Dataset
df = pd.read_csv("C:/Users/HP/Downloads/archive (1)/House Price India.csv", index_col=0)

df.head()

,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
id,,,,,,,,,,,,,,,,,,,,,
6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,8,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,8,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,9,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,8,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,9,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [6]:
#Check Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14619 entries, 6762810635 to 6762831463
Data columns (total 22 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Date                                   14619 non-null  int64
 1   number of bedrooms                     14619 non-null  int64
 2   number of bathrooms                    14619 non-null  float64
 3   living area                            14619 non-null  int64
 4   lot area                               14619 non-null  int64
 5   number of floors                       14619 non-null  float64
 6   waterfront present                     14619 non-null  int64
 7   number of views                        14619 non-null  int64
 8   condition of the house                 14619 non-null  int64
 9   grade of the house                     14619 non-null  int64
 10  Area of the house(excluding basement)  14619 non-null  int64
 11  Area of the basement                   14619 non-null  int64
 12  Built Year                             14619 non-null  int64
 13  Renovation Year                        14619 non-null  int64
 14  Postal Code                            14619 non-null  int64
 15  Lattitude                              14619 non-null  float64
 16  Longitude                              14619 non-null  float64
 17  living_area_renov                      14619 non-null  int64
 18  lot_area_renov                         14619 non-null  int64
 19  Number of schools nearby               14619 non-null  int64
 20  Distance from the airport              14619 non-null  int64
 21  Price                                  14619 non-null  int64
dtypes: float64(4), int64(18)
memory usage: 2.6 MB

In [7]:
#Define Features and Target
X = df.drop(columns=['Price'])
y = df['Price']

In [8]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
#1- LINEAR REGRESSION
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

In [16]:
#Predict & Evaluate
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

pred_lr = lr.predict(X_test)

print("1.Linear Regression-")

print("MAE:", mean_absolute_error(y_test, pred_lr))
print("MSE:", mean_squared_error(y_test, pred_lr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred_lr)))
print("R2:", r2_score(y_test, pred_lr))

1.Linear Regression-
MAE: 125366.179374492
MSE: 44107941320.9564
RMSE: 210018.9070559039
R2: 0.7019654586300876

In [17]:
#2-Decision Tree
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [18]:
#Predict & Evaluate
pred_dt = dt.predict(X_test)

print("2.Decision Tree-")

print("MAE:", mean_absolute_error(y_test, pred_dt))
print("MSE:", mean_squared_error(y_test, pred_dt))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred_dt)))
print("R2:", r2_score(y_test, pred_dt))

2.Decision Tree-
MAE: 97580.97674418605
MSE: 35482141260.212036
RMSE: 188367.0386777157
R2: 0.7602494385226402

In [19]:
#3-Random Forest
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)

rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [24]:
#Predict & Evaluate
pred_rf = rf.predict(X_test)

print("3.Random Forest-")

print("MAE:", mean_absolute_error(y_test, pred_rf))
print("MSE:", mean_squared_error(y_test, pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred_rf)))
print("R2:", r2_score(y_test, pred_rf))

3.Random Forest-
MAE: 70166.53344733242
MSE: 17628652849.854855
RMSE: 132772.93718922866
R2: 0.8808843190199028

In [25]:
#4-Gradient Boosting
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor()

gb.fit(X_train, y_train)

GradientBoostingRegressor()

In [26]:
#Predict & Evaluate
pred_gb = gb.predict(X_test)

print("4.Gradient Boosting-")

print("MAE:", mean_absolute_error(y_test, pred_gb))
print("MSE:", mean_squared_error(y_test, pred_gb))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred_gb)))
print("R2:", r2_score(y_test, pred_gb))

4.Gradient Boosting-
MAE: 77412.95970949827
MSE: 17086726976.33272
RMSE: 130716.20777980334
R2: 0.884546077522672

In [27]:
#5-svr
from sklearn.svm import SVR

svr = SVR()

svr.fit(X_train, y_train)

SVR()

In [28]:
#Predict & Evaluate
pred_svr = svr.predict(X_test)

print("SVR")

print("MAE:", mean_absolute_error(y_test, pred_svr))
print("MSE:", mean_squared_error(y_test, pred_svr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, pred_svr)))
print("R2:", r2_score(y_test, pred_svr))

SVR
MAE: 226394.30665702937
MSE: 155771232817.1538
RMSE: 394678.6449976155
R2: -0.05253626764096797

In [29]:
#Final Comparison
results = pd.DataFrame({
    "Actual Price": y_test.values,
    "Linear Regression": pred_lr,
    "Decision Tree": pred_dt,
    "Random Forest": pred_rf,
    "Gradient Boosting": pred_gb,
    "SVR": pred_svr
})

results.head(10)

,Actual Price,Linear Regression,Decision Tree,Random Forest,Gradient Boosting,SVR
0,546800,5.409919e+05,615000.0,585745.99,6.145008e+05,450449.081016
1,550000,4.950922e+05,475000.0,432118.77,3.978361e+05,450447.840946
2,399950,5.427493e+05,299000.0,368718.63,4.247284e+05,450164.728245
3,940000,8.220305e+05,815241.0,804419.55,7.455958e+05,450622.372174
4,545000,7.347788e+05,480000.0,517526.70,5.839879e+05,450568.446560
5,318000,3.476500e+05,310000.0,287987.79,3.122323e+05,450069.244088
6,315000,3.272753e+05,285000.0,342230.00,3.106907e+05,449681.386382
7,1800000,1.389582e+06,2450000.0,2070685.00,1.853578e+06,450738.601037
8,1250000,1.087105e+06,550000.0,787925.81,1.050429e+06,450725.909147
9,825000,1.045981e+06,677000.0,854814.34,9.416344e+05,451128.859081