## Importing all the Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# Displaying the dataset
df = pd.read_csv("../dataset/df_transformed.csv")
df.tail()

,Rooms,Price,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,...,Sale_Method_Sold_Prior,Sale_Method_Vendor_Bid,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
13575,4,1245000.0,16.7,2.0,2.0,652.0,126.00,1981.0,-37.90562,145.16761,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13576,3,1031000.0,6.8,2.0,2.0,333.0,133.00,1995.0,-37.85927,144.87904,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13577,3,1170000.0,6.8,2.0,4.0,436.0,126.00,1997.0,-37.85274,144.88738,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13578,4,2500000.0,6.8,1.0,5.0,866.0,141.85,1920.0,-37.85908,144.89299,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13579,4,1285000.0,6.3,1.0,1.0,362.0,112.00,1920.0,-37.81188,144.88449,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [3]:
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=["Price"])
y = df["Price"]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Linear Regression Model

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [8]:
y_pred_linear= model.predict(X_test_scaled)

In [9]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred_linear)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_linear))
mse = mean_squared_error(y_test, y_pred_linear)
r2 = r2_score(y_test, y_pred_linear)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 262569.17940437945
MSE: 142825915518.2153
RMSE: 377923.16086502996
R²: 0.6404306796906716

## RandomForestModel

In [10]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

In [11]:
mae = mean_absolute_error(y_test, y_pred_rf)
mse = mean_squared_error(y_test, y_pred_rf)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_rf)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 164964.46558296515
MSE: 72925787991.68106
RMSE: 270047.7513175791
R²: 0.8164067359480939

## Ridge Regression Model

In [12]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)
ridge.fit(X_train_scaled, y_train)

Ridge()

In [13]:
y_pred_ridge = ridge.predict(X_test_scaled)

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred_ridge)
mse = mean_squared_error(y_test, y_pred_ridge)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_ridge)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 262566.09635969327
MSE: 142826231206.75833
RMSE: 377923.5785271386
R²: 0.6404298849335406

## Lasso Regression Model

In [15]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=1.0,max_iter=2000000)
lasso.fit(X_train_scaled, y_train)

Lasso(max_iter=2000000)

In [16]:
y_pred_lasso = lasso.predict(X_test_scaled)

In [17]:
mae = mean_absolute_error(y_test, y_pred_lasso)
mse = mean_squared_error(y_test, y_pred_lasso)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_lasso)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 262298.86347723886
MSE: 142554750255.08524
RMSE: 377564.2332836696
R²: 0.6411133478815346

## Gradient Boosting

In [18]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(n_estimators=500,learning_rate=0.05,max_depth=4,random_state=42)
gb.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=4, n_estimators=500,
                          random_state=42)

In [19]:
y_pred_gb = gb.predict(X_test)

In [20]:
mae = mean_absolute_error(y_test, y_pred_gb)
mse = mean_squared_error(y_test, y_pred_gb)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_gb)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 163129.9786398733
MSE: 65570010290.44226
RMSE: 256066.41773267
R²: 0.8349251678362033

In [21]:
pd.options.display.float_format = '{:,.0f}'.format
comparison = pd.DataFrame({
    "Actual_Price": y_test.reset_index(drop=True),
    "Linear_Pred": y_pred_linear,
    "Ridge_Pred": y_pred_ridge,
    "Lasso_Pred": y_pred_lasso,
    "RandomForest_Pred": y_pred_rf,
    "GradientBoost_Pred": y_pred_gb
})

comparison.head(20)

,Actual_Price,Linear_Pred,Ridge_Pred,Lasso_Pred,RandomForest_Pred,GradientBoost_Pred
0,"2,600,000","1,612,266","1,612,261","1,612,265","2,384,780","2,159,160"
1,"620,000","400,533","400,514","400,538","616,722","570,844"
2,"1,000,000","967,089","967,071","967,092","1,071,932","885,332"
3,"430,000","544,257","544,316","544,256","540,060","496,826"
4,"392,250","712,325","712,337","712,339","946,440","720,700"
5,"700,000","863,353","863,392","863,358","814,861","703,222"
6,"439,000","190,659","190,670","190,658","481,590","473,928"
7,"2,236,000","1,597,868","1,597,848","1,597,867","1,555,550","1,636,424"
8,"671,000","599,225","599,285","599,236","593,318","569,541"
9,"1,870,000","1,453,520","1,453,476","1,453,519","1,660,940","1,478,709"
10,"2,525,000","1,938,296","1,938,224","1,938,290","2,347,340","2,353,786"
11,"710,000","1,024,861","1,024,824","1,024,844","660,778","642,740"
12,"1,330,000","964,182","964,152","964,182","1,018,990","1,125,356"
13,"642,500","736,044","736,076","736,039","598,455","699,981"
14,"731,000","428,908","428,910","428,899","671,667","605,539"
15,"860,000","955,254","955,303","955,257","905,965","1,132,134"
16,"429,000","363,279","363,293","363,278","476,455","494,319"
17,"790,500","795,142","795,180","795,147","752,605","743,953"
18,"2,350,000","2,077,023","2,076,996","2,077,018","2,582,220","2,519,702"
19,"330,000","283,195","283,168","283,180","428,940","361,880"

## XGBRegressor Model

In [ ]:
#from xgboost import XGBRegressor